In [3]:
import numpy as np

**Error handling**

>1․ Եթե որպես ֆունկցիայի պարամետր ստանում եք numpy զանգված (վեկտոր կամ մատրից), և այն չի համապատասխանում խնդրում նշված չափին (dimensions) կամ չափերի անհամաձայնություններ կան, ապա վերադարցրեք(return) **"DimensionError"** տեքստը

>2․ Եթե որպես ֆունկցիայի պարամետր ստանում եք 2D numpy զանգված (մատրից), և այն հակադարձելի(invertable) չէ, հակառակ խնդրի պահանջի, ապա վերադարցրեք(return) **"NotInvertableError"** տեքստը

# Problems

Problem 1. Compute the euclidean distance between two arrays. 


> Հաշվիր 2 զանգվածների Էվկլիդյան հեռավորությունը։


```
a, b = np.array([1, 2]), np.array([1, 3])
print(dist(a, b))
>>1
```


In [46]:
def dist(a, b):
    summ = 0
    if len(a) != len(b):
        return 'DimensionError'
    else:
        for i, j in zip(a, b):
            summ += ((i - j) ** 2)
        return summ ** 0.5
    

In [47]:
# Do not modify this cell
a, b = np.array([1, 1]), np.array([1, 3])
assert dist(a, b) == 2

a, b = np.array([-10, 1.5]), np.array([0.9, 3.6])
assert round(dist(a, b), 2) == 11.1

a, b = np.array([1, 1, 1]), np.array([0, -1, 3])
assert dist(a, b) == 3

a, b = np.array([1, 0, -999]), np.array([1, 3])
assert dist(a, b) == "DimensionError"

a, b = np.array([10, -1, 9, 1, 2.98, -0.14]), np.array([0, -1, 3.14, np.pi, 99, np.e])
assert round(dist(a, b), 2) == 96.78

Problem 2. Normalize an array so the values range exactly between 0 and 1․

> Նորմավորիր զանգվածը այնպես, որ արժեքները լինեն 0-ից 1 միջակայքում։

```
a = np.array([1,2,3,4])
print(rescale(a))
>>[0, 0.3333333, 0.66666667, 1]
```



In [48]:
1.
import numpy as np
def rescale(a):
    norm = (a - np.min(a)) / (np.max(a) - np.min(a))
    return norm
  #Your code here

In [49]:

# Do not modify this cell
assert np.all(rescale(np.array([1, 2, 3, 4])) == [0, 1/3, 2/3, 1])
assert np.all(rescale(np.array([0, 1])) == [0, 1])
assert np.all(rescale(np.array([0, 10])) == [0, 1])
assert np.all(rescale(np.array([1, 2, 4])) == [0, 1/3, 1])

Problem 3. Given a numpy array 'a' that contains n elements, denote by b the set of its unique values ​​in ascending order, denote by m the size of array b. You need to create a numpy array with dimensions $n \times m$, in each row of which there must be a value of 1 in case it is equal to the value of the given index of array b, in other places it must be 0.

> Տրված է numpy զանգված 'a', որը պարունակում է n էլեմենտ, b-ով նշանակենք նրա ունիկալ արժեքների (արժեքներն առանց կրկնության) զանգվածը ըստ աճման կարգի, m-ով նշանակենք b զանգվածի չափը: Հարկավոր է ստեղծել numpy զանգված $n \times m$ չափերով, որի i-րդ տողի j-րդ սյան տեղում պետք է գրված լինի 1 այն դեպքում, երբ a-ի i-րդ անդամը հավասար է b֊ի j-րդ արժեքին, իսկ մնացած տեղերում պետք է լինեն 0֊ներ։


```
a = np.array([1, 1, 2, 3, 2, 4])
# b = np.array([1, 2, 3, 4])
print(convert(a))
>>[[1, 0, 0, 0],
  [1, 0, 0, 0],
  [0, 1, 0, 0],
  [0, 0, 1, 0]
  [0, 1, 0, 0],
  [0, 0, 0, 1]]
```



In [50]:
3.
import numpy as np

def convert(a):
    b = np.unique(a)
    k = np.zeros((len(a), len(b)), dtype=int)
    for i in range(len(a)):
        for j in range(len(b)):
            if a[i] == b[j]:
                k[i, j] = 1
    return k
  #Your code here

In [51]:
# Do not modify this cell
assert np.all(convert(np.array([0, 0, 2, 3, 2, 4])) ==
              [[1, 0, 0, 0],
               [1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 1, 0, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([-np.pi, 9])) ==
              [[1, 0],
               [0, 1]])

assert np.all(convert(np.array([-1, 1, 9, 10])) ==
              [[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([np.sqrt(2), np.sqrt(2), np.sqrt(2)])) ==
              [[1],
               [1],
               [1]])

Problem 4. Given a 2D numpy array 'a' of sizes $n \times m$. You need to pad the matrix with 0s so that the dimensions of the matrix become  $(n+2n_1) \times (m+2m_1)$
>Տրված է 2D numpy զանգված 'a' $n \times m$ չափերի, Հարկավոր է կողքերից հավասարաչափ 0-ներ ավելացնել այնպես, որ զանգվածի չափերը դառնան $(n+2n_1) \times (m+2m_1)$

```
a = np.array([[1, 1], [1, 1]])
n1 = 1
m1 = 2
print(padding(a, n1, m1))
>>[[0, 0, 0, 0, 0, 0], 
  [0, 0, 1, 1, 0, 0],
  [0, 0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0, 0]]
```



In [68]:
4.
import numpy as np

n = [1, 2]
m = [3, 4]
a = np.array([n, m]) 
n1 = 0
m1 = 2

def padding(a, n1, m1):
    if n1 == 0 and m1 == 0:
        return a
    else:
        x = np.zeros((a.shape[0] + 2 * n1, a.shape[1] + 2 * m1))
        if n1 != 0:
            x[n1:n1 + a.shape[0], m1:m1 + a.shape[1]] = a
        else:
            x[:, m1:m1 + a.shape[1]] = a
        return x
    
print(padding(a, n1, m1))

[[0. 0. 1. 2. 0. 0.]
 [0. 0. 3. 4. 0. 0.]]


In [69]:
# Do not modify this cell
assert np.all(padding(np.array([[1, 1], [1, 1]]), 1, 2) ==
              [[0, 0, 0, 0, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 0, 0, 0, 0]])

assert np.all(padding(np.array([[1, 2], [1, 1]]), 0, 2) ==
              [[0, 0, 1, 2, 0, 0],
               [0, 0, 1, 1, 0, 0]])

assert np.all(padding(np.array([[9]]), 2, 2) ==
              [[0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 9, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

Problem 5. Given 2D numpy arrays 'a' and 'b' of sizes $m \times n$ and $k \times k$ respectively (k <= n, k <= m), 2 integers 'stride' and 'padding' and 'f' function. You need to 
  1. first pad 'a' matrix with 0s on each side, 
  2. then move 'b'  over 'a' with stride 'stride', then multiply their elements by the corresponding 'b' elements, 
  3. add the resulting k * k numbers 
  4. apply the 'f' function to the result 
  5. and place them in the new matrix.

  Տրված է 2D numpy զանգվածներ 'a' և 'b' համապատասխանաբար $m \times n$ և $k \times k$ չափերի (k<=n, k<=m), 2 ամբողջ թվեր 'stride' և 'padding' ու 'f' ֆունկցիա։ Հարկավոր է

  1․ 'a' մատրիցին 'padding' չափով 0֊ներ ավելացնել յուրաքանչյուր կողմից,

  2․ ապա 'b'֊ն 'stride' քայլով "շարժել" 'a'֊ի վրայով և 'a'֊ի համապատասխան էլեմենտները բազմապատկել 'b'-ի համապատասխան էլեմենտներով,

  3․ ստացված k*k հատ թվերը գումարել,

  4․ արդյունքի վրա կիրառել 'f' ֆունկցիան

  5․ և տեղադրել նոր մատրիցում։

```
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0],
              [4, 5, 2]])
b = np.array([[1, 0],
              [0, 1]])

stride = 1
padding = 0
f = lambda x: x**2
print(conv(a, b, stride, padding, f))
>>[[4, 16],
  [9, 1],
  [36, 25]]
```
![ConvUrl](https://miro.medium.com/max/2340/1*Fw-ehcNBR9byHtho-Rxbtw.gif "conv")


In [168]:
def conv(a, b, stride, pad, f):
    m = np.shape(a)[0]
    n = np.shape(a)[1] 
    k = np.shape(b)[0]

    if k > n or k > m or b.shape[0] != b.shape[1]:
        return 'DimensionError'
    
    result = []
    m1 = 2 * pad + m
    n1 = 2 * pad + n
    arr = np.zeros((m1, n1), dtype=int)
    arr[pad:pad+m, pad:pad+n] = a
    for i in range(0, m1 + 1 - k, stride):
        for j in range(0, n1 + 1 - k, stride):
            result.append(f(np.sum(a[i:i+k,j:j+k]*b)))
    result = np.array(result).reshape(m1 + 1 - k, n1 + 1 - k)
    return result

In [169]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([[1, 0],
              [0, 1]])
f = lambda x: x**2
assert np.all(conv(a, b, 1, 0, f) ==
              [[4., 16.],
               [9.,  1.]])

a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0],
              [-10, -3, 0]])
b = np.arange(9).reshape(3, 3)
f = lambda x:0 if x<0 else x
assert np.all(conv(a, b, 1, 0, f) ==
              [[51.],
               [0.]])

b = np.arange(6).reshape(2, 3)
assert conv(a, b, 1, 0, f) == "DimensionError"

In [135]:
list(range(0, 1, 1))

[0]

Problem 6. Given a 2D numpy array 'a' of sizes $m \times n$ whose each line is labeled with 0 or 1 numbers and a  vector  (of size n) which is not labeled. You need to find the appropriate label for 'b'. In the 'a' matrix, find the line closest to 'b' (according to the Euclidean distance) and label 'b' with the label of that line.
>Տրված է $m \times n$ չափանի 2D numpy զանգված՝ 'a', որի յուրաքանչյուր տող պիտակավորված (label) է 0 կամ 1 թվերով և 'b' վեկտոր (n չափի) որը պիտակավորված չէ։ Հարկավոր է գտնել 'b'֊ի համապատասխան պիտակը (label)՝ գտնելով 'a' մատրիցում 'b'ին ամենամոտ  տողը (ըստ Էվկլիդյան հեռավորության) և 'b'֊ն պիտակավորեք այդ տողի պիտակով։

```
a = np.array([[1, -2],
              [2, 5],
              [-3, -10],
              [3, 2],
              [3, 2],
              [0, 1]])
labels = np.array([0,1,0,1,1,0])
b = np.array([10,10])
print(predict_label(a,labels,b))
>>1
```



In [437]:
import numpy as np

def predict_label(a, labels, b):
    if a.shape[1] != len(b):
        return 'DimensionError'
    distances = []
    for i in range(len(a)):
        distance = (np.linalg.norm(b-a[i]), labels[i])  
        distances.append(distance)
    min_distance = min(distances)  
    return min_distance[1]  


In [439]:
# Do not modify this cell
a = np.array([[1, -2],
              [2, 5],
              [-3, -10],
              [3, 2],
              [3, 2],
              [0, 1]])
labels = np.array([0, 1, 0, 1, 1, 0])

assert predict_label(a, labels, np.array([10, 10])) == 1
assert predict_label(a, labels, np.array([10, -10])) == 0
assert predict_label(a, labels, np.array([10, -1])) == 1
assert predict_label(a, labels, np.array([1, 1, 0])) == "DimensionError"
    
a = np.array([[0, 1, -2],
              [2, 1, 5],
              [-3, 3.5, -10],
              [3, 2, 9],
              [3, -2, 9]])
labels = np.array([0, 1, 0, 1, 1])
assert predict_label(a, labels, np.array([1])) == "DimensionError"
assert predict_label(a, labels, np.array([1, 1, 0])) == 0
assert predict_label(a, labels, np.array([1, 1, 10])) == 1

Problem 7. Given a 2D numpy array 'a' of sizes $m \times n$ with missing elements (NAN) and a string 'mode' $\in$ {"mean","min","max"}. You need to write the {"mean","min","max"} ('mode') of the corresponding column instead of the missing elements.
>Տրված է 2D numpy զանգված 'a' $m \times n$ չափերի, որն ունի բացակայող էլեմենտներ (NAN) ու տեքստային փոփոխական 'mode' $\in$ {"mean","min","max"}։ Հարկավոր է 'a' մատրիցի բացակայող էլեմենտների փոխարեն գրել համապատասխան սյան {միջինը, մինիմումը, մաքսիմումը} ըստ 'mode' փոփոխականի։

```
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])
mode = "mean"
print(fill(a, mode))
>>[[  0.75 200.    10.  ]
 [  2.   110.    10.  ]
 [  0.   120.    11.  ]
 [  0.   400.    10.  ]
 [  1.   207.5    9.  ]]
```



In [10]:
import numpy as np

a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])

def fill(a, mode=None):
    if mode == "min":
        mode_value = np.nanmin(a, axis=0)  
    elif mode == "max":
        mode_value = np.nanmax(a, axis=0)
    elif mode == "mean":
        mode_value = np.nanmean(a, axis=0)
        
    else:
        raise ValueError("Invalid mode specified")
        
    for i in range(len(a)):
        for j in range(len(a[i])):
            if np.isnan(a[i][j]):
                a[i][j] = mode_value[j]
    return a

output = fill(a, mode="min")
print(output)


[[  0. 200.  10.]
 [  2. 110.   9.]
 [  0. 120.  11.]
 [  0. 400.   9.]
 [  1. 110.   9.]]


In [11]:
# Do not modify this cell
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])

assert np.all(fill(a, "mean") ==
              [[0.75, 200.,  10.],
               [2., 110.,  10.],
               [0., 120.,  11.],
               [0., 400.,  10.],
               [1., 207.5,   9.]])

a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])

output_min = fill(a, mode="min")
print(output_min)


[[  0. 200.  10.]
 [  2. 110.   9.]
 [  0. 120.  11.]
 [  0. 400.   9.]
 [  1. 110.   9.]]


Problem 9. Given a numpy matrix 'a' of sizes $m \times n$ and the numbers 'k' and 'q' in the range [0,1]. You need to randomly select the 'k' part of the rows of 'a' (can be repeated) and the 'q' part of their columns (should not be repeated).
>Տրված է numpy մատրից 'a' $m \times n$ չափերի և [0,1] միջակայքի 'k' և 'q' թվեր։ Հարկավոր է պատահականորեն ընտրել 'a'ի տողերի 'k' մասը (կարող են կրկնվել) և դրանց սյուների 'q' մասը (չպետք է կրկնվեն)։

```
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
k = 0.25
q = 0.6
print(rand_rows_cols(a, k, q))
>>[[83, 110],
  [3, 65]]
```


In [12]:
def rand_rows_cols(a, k, q):
    row = int(a.shape[0] * k)
    col = int(a.shape[1] * q)
    
    np.random.seed(30)  
    
    rows = np.random.choice(a.shape[0], size=row, replace=False)
    cols = np.random.choice(a.shape[1], size=col, replace=False)
    
    return a[rows][:, cols]

# Test the function
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])

k = 0.25
q = 0.6
print(rand_rows_cols(a, k, q))

[[5]
 [3]]


Problem 10. Given a numpy matrix 'a' of sizes $m \times n$. You need to find the rows of 'a' whose sum of elements is in the range [100,200).
>Տրված է $m \times n$ չափերի numpy մատրից 'a'։ Հարկավոր է գտնել 'a'-ի այն տողերը՝ որոնց էլեմենտների գումարը գտնվում է [100,200) միջակայքում։

```
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
print(between_100_200(a))
>[[0, 108, 3],
  [5, 83, 110],
  [8, 9, 103]]
```


In [13]:
import numpy as np

def between_100_200(a):
    row_sums = np.sum(a, axis=1)
    return a[(row_sums >= 100) & (row_sums < 200)]

In [14]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
assert np.all(between_100_200(a) ==
              [[0, 108,   3],
               [5,  83, 110],
               [8,   9, 103]])

a = np.array([[1, 1, 2],
              [0, -108, 3],
              [1, 3, 65],
              [50, 35, 5]])
assert len(between_100_200(a)) == 0

Problem 10. Get the L in the Cholesky decomposition of x.

> Գտիր x-ի Չոլեսկու դեկոմպոզիցիայի L-ը:


```
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
print(Cholesky(x))
>>[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
```



In [15]:
def Cholesky(x):
    print(np.linalg.cholesky(x))
    return np.linalg.cholesky(x)
  #your code here

In [16]:
# Do not modify this cell
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
assert np.all(Cholesky(x) ==
              [[2.,  0.,  0.],
               [6.,  1.,  0.],
               [-8.,  5.,  3.]])

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Problem 12. Write a function to return a 2d array of given size with 1s on the border and 0s inside. 

Գրել ֆունկցիա, որը կվերադարձնի տրված չափանի երկչափ numpy array (քառակուսի մատրից), որտեղ եզրերում կլինեն 1-եր, իսկ ներսում՝ 0-ներ։  



In [17]:
import numpy as np

def zero_one(x):
    arr = np.ones((x, x), dtype=int)  
    print(arr)
    arr[1:-1, 1:-1] = 0
    return arr

In [19]:
assert np.array_equal(zero_one(3), np.array([[1., 1., 1.],
                                            [1., 0., 1.],
                                            [1., 1., 1.]]))
assert np.array_equal(zero_one(4), np.array([[1., 1., 1., 1],
                                            [1., 0., 0., 1],
                                            [1., 0., 0., 1],
                                            [1., 1., 1., 1]]))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
